'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SIA.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property AyudaExcel_1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AyudaExcel 1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property AyudaExcel_11() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AyudaExcel 11", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property AyudaExcel_2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AyudaExcel 2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasAlumnosNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasAlumnosNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasAlumnosSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasAlumnosSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasFeriadoNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasFeriadoNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasFeriadoSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasFeriadoSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasGrupoNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasGrupoNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasGrupoSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasGrupoSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasHorariosNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasHorariosNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasHorariosSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasHorariosSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAltasSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAltasSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAyudaNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAyudaNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAyudaSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAyudaSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCancelarNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCancelarNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCancelarSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCancelarSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCargarHuellaNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCargarHuellaNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCargarHuellaSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCargarHuellaSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnConsultarAsistenciaNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnConsultarAsistenciaNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnConsultarAsistenciaSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnConsultarAsistenciaSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnConsultasNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnConsultasNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnConsultasNo1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnConsultasNo1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnConsultasSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnConsultasSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnConsultasSi1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnConsultasSi1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCursoNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCursoNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCursoSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCursoSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnEliminarNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnEliminarNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnEliminarSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnEliminarSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnGuardarNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnGuardarNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnGuardarSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnGuardarSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoAsignarHuellasNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoAsignarHuellasNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoAsignarHuellasSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoAsignarHuellasSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoAsistenciaNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoAsistenciaNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoAsistenciaSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoAsistenciaSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoHorariosNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoHorariosNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoHorariosSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoHorariosSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoMovAlumnosNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoMovAlumnosNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoMovAlumnosSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoMovAlumnosSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoNo1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoNo1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoRetiroAnticipadoNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoRetiroAnticipadoNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoRetiroAnticipadoSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoRetiroAnticipadoSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnManejoSi1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnManejoSi1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnModificarNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnModificarNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnModificarSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnModificarSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnNuevoNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnNuevoNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnNuevoSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnNuevoSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnPlanillaDeAlumnosNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnPlanillaDeAlumnosNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnPlanillaDeAlumnosSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnPlanillaDeAlumnosSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSalirNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSalirNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSalirNo1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSalirNo1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSalirSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSalirSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSalirSi1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSalirSi1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSistemaNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSistemaNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSistemaSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSistemaSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnVolverNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnVolverNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnVolverSi() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnVolverSi", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Cartel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Cartel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Cartelito() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Cartelito", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property CartelitoT() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("CartelitoT", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Fondo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Fondo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property fondo_azul_blue_cuadros_fotorecurso() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("fondo-azul-blue-cuadros-fotorecurso", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Fondo1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Fondo1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Fondo2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Fondo2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property FondoD() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("FondoD", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property FondoDEF() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("FondoDEF", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property HuellaLibre() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("HuellaLibre", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property HuellaLibreGris() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("HuellaLibreGris", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property IconoHuellaNo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("IconoHuellaNo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property IconoHuellaOk() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("IconoHuellaOk", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Image1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Image1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ll() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ll", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Panel1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property panelito() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("panelito", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property panelito2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("panelito2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property SIAT() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("SIAT", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
